name: Run Command for Changed Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
      - name: install jsonrepair
        id: jsonrepair-install
        run: |
            npm install -g jsonrepair

      - name: Get changed files from the last 10 commits
        id: changed-files
        run: |
          git fetch --depth=2
          git diff --name-only > changed_files.txt

      - name: Run command for each changed file
        run: |
          while IFS= read -r file; do
            echo "Processing $file"
            jsonrepair /data/$file --overwrite
          done < changed_files.txt

      - name: Commit files # only runs if something actually changed
        run: |
          if [[ -n "$(git status -s)" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "CI: Automatic Rustfmt" -a
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GIT_TOKEN }}